deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  server:
    http_listen_port: 3100
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
    - from: "2025-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem
      schema: v13
chunksCache:
  enabled: true
  allocatedMemory: 1024
singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0